// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeguroCelular.Mvc.Models.Data;

namespace SeguroCelular.Mvc.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221027165015_MM03")]
    partial class MM03
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SeguroCelular.Mvc.Models.CotacaoSeguro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CotacaoSeguroId")
                        .HasColumnType("int");

                    b.Property<string>("ModeloCelular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorCotacao")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CotacaoSeguroId");

                    b.ToTable("CotacaoSeguro");
                });

            modelBuilder.Entity("SeguroCelular.Mvc.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SeguroCelular.Mvc.Models.CotacaoSeguro", b =>
                {
                    b.HasOne("SeguroCelular.Mvc.Models.User", "User")
                        .WithMany("Cotacoes")
                        .HasForeignKey("CotacaoSeguroId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SeguroCelular.Mvc.Models.User", b =>
                {
                    b.Navigation("Cotacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
